using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BoletoBr.Enums
{
    public enum EnumCodigoOcorrenciaRetorno
    {
        //Ocorrências para arquivo retorno
        RetTituloNaoExiste,
        RetRegistroConfirmado,
        RetRegistroRecusado,
        RetComandoRecusado,
        RetLiquidado,
        RetLiquidadoEmCartorio,
        RetLiquidadoParcialmente,
        RetLiquidadoSaldoRestante,
        RetLiquidadoSemRegistro,
        RetLiquidadoPorConta,
        RetBaixaSolicitada,
        RetBaixado,
        RetJaBaixado,
        RetBaixaAutomatica,
        RetBaixadoPorDevolucao,
        RetBaixadoFrancoPagamento,
        RetBaixaPorProtesto,
        RetRecebimentoInstrucaoBaixar,
        RetBaixaOuLiquidacaoEstornada,
        RetTituloEmSer,
        RetRecebimentoInstrucaoConcederAbatimento,
        RetAbatimentoConcedido,
        RetRecebimentoInstrucaoCancelarAbatimento,
        RetAbatimentoCancelado,
        RetRecebimentoInstrucaoConcederDesconto,
        RetDescontoConcedido,
        RetRecebimentoInstrucaoCancelarDesconto,
        RetDescontoCancelado,
        RetRecebimentoInstrucaoAlterarDados,
        RetDadosAlterados,
        RetRecebimentoInstrucaoAlterarVencimento,
        RetVencimentoAlterado,
        RetAlteracaoDadosNovaEntrada,
        RetAlteracaoDadosBaixa,
        RetRecebimentoInstrucaoProtestar,
        RetNaoProtestar,
        RetProtestado,
        RetRecebimentoInstrucaoSustarProtesto,
        RetProtestoSustado,
        RetInstrucaoProtestoRejeitadaSustadaOuPendente,
        RetDebitoEmConta,
        RetRecebimentoInstrucaoAlterarNomeSacado,
        RetNomeSacadoAlterado,
        RetRecebimentoInstrucaoAlterarEnderecoSacado,
        RetEnderecoSacadoAlterado,
        RetEncaminhadoACartorio,
        RetRetiradoDeCartorio,
        RetRecebimentoInstrucaoDispensarJuros,
        RetJurosDispensados,
        RetManutencaoTituloVencido,
        RetRecebimentoInstrucaoAlterarTipoCobranca,
        RetTipoCobrancaAlterado,
        RetDespesasProtesto,
        RetDespesasSustacaoProtesto,
        RetDebitoCustasAntecipadas,
        RetCustasCartorioDistribuidor,
        RetCustasEdital,
        RetProtestoOuSustacaoEstornado,
        RetDebitoTarifas,
        RetAcertoDepositaria,
        RetProrrogVencto,
        RetConfirmacaoProtesto,
        RetTituloDdaReconhecido,
        RetTituloDdaNaoReconhecido,
        RetTituloDdaRecusado,
        RetOutrasOcorrencias
    }
}
